# Generated by Django 5.0.6 on 2024-07-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_entrenadores_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clases',
            new_name='Clase',
        ),
        migrations.RenameModel(
            old_name='Entrenadores',
            new_name='Entrenador',
        ),
        migrations.RenameModel(
            old_name='Socios',
            new_name='Socio',
        ),
    ]
