# Generated by Django 5.0.6 on 2024-08-13 23:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_yoga'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva_clase',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reserva_clase',
            name='turno',
            field=models.CharField(choices=[('Yoga_Lu_Mañana', 'Yoga_Lunes_ 10:00AM - 11:30AM'), ('Yoga_Mar_Tarde', 'Yoga_Martes_ 2:00PM - 3:30PM'), ('Pilates_Jue_Tarde', 'Pilates_Jueves_ 2:00PM - 3:30PM'), ('Pilates_Vie_Mañana', 'Pilates_Viernes_ 10:00AM - 11:30AM'), ('Zumba_Lu_Tarde', 'Zumba_Lunes_ 2:00PM - 3:30PM'), ('Zumba_Mar_Mañana', 'Zumba_Martes_ 10:00AM - 11:30AM'), ('Spinning_Mie_Mañana', 'Spinning_Miércoles_ 10:00AM - 11:30AM'), ('Spinning_Vie_Tarde', 'Spinning_Viernes_ 2:00PM - 3:30PM'), ('Musculación_Mie_Mañana', 'Musculación_Miércoles_ 10:00AM - 11:30AM'), ('Musculación_Jue_Tarde', 'Musculación_Jueves_ 2:00PM - 3:30PM')], default='----', max_length=50),
        ),
    ]
